name: LINK Crawler

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: true  # Ensure Git LFS is checked out properly

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Git LFS
      run: |
        sudo apt-get install git-lfs
        git lfs install

    - name: Run RSS Crawler
      run: python rss_crawler_module/cronjob_crawl_feed_links.py

    - name: Commit and push if it changed
      run: |
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update rss_links.db scheduled" || exit 0
        git push --force-with-lease
      env:
        GIT_AUTHOR_NAME: GitHub Action
        GIT_AUTHOR_EMAIL: action@github.com
        GIT_COMMITTER_NAME: GitHub Action
        GIT_COMMITTER_EMAIL: action@github.com

    - name: Push changes if workflow is cancelled
      if: cancelled()
      run: |
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update rss_links.db due to workflow cancellation" || exit 0
        git push --force-with-lease
      env:
        GIT_AUTHOR_NAME: GitHub Action
        GIT_AUTHOR_EMAIL: action@github.com
        GIT_COMMITTER_NAME: GitHub Action
        GIT_COMMITTER_EMAIL: action@github.com

    - name: Push changes if workflow runs in error
      if: failure()
      run: |
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update rss_links.db due to workflow error" || exit 0
        git push --force-with-lease
      env:
        GIT_AUTHOR_NAME: GitHub Action
        GIT_AUTHOR_EMAIL: action@github.com
        GIT_COMMITTER_NAME: GitHub Action
        GIT_COMMITTER_EMAIL: action@github.com

